sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rpawan48/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rpawan48/react-test npm test

after_success:
  - docker build -t rpawan48/multi-client ./client
  - docker build -t rpawan48/multi-nginx ./nginx
  - docker build -t rpawan48/multi-server ./server
  - docker build -t rpawan48/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rpawan48/multi-client
  - docker push rpawan48/multi-nginx
  - docker push rpawan48/multi-server
  - docker push rpawan48/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: Multi-Docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-921614905458
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
